### ISSUE TITLE
Bug: TypeError: Cannot read property 'lineNumber' of undefined

### ISSUE THREAD

**Issue by OskarsEzerins** [zombocom/dead_end-vscode#1]
Hi,

When there is a missing end, the plugin works just fine and displays the error as expected.
But when a ruby file is saved withot any ruby syntax errors, below exception is raised.

P.S. Thanks for the plugin and the time spent developing it. :+1: 

OS: Ubuntu
Gem is installed in a project via bundler, gemfile in development dep.

```javascript
ERR Cannot read property 'lineNumber' of undefined: TypeError: Cannot read property 'lineNumber' of undefined
    at /home/user/.vscode/extensions/zombocom.dead-end-vscode-0.1.2/extension.js:37:23
    at ChildProcess.exithandler (child_process.js:303:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

**Comment by schneems** [comment]
Hi. Thanks for the report. It's odd that this isn't catching the output https://github.com/zombocom/dead_end-vscode/blob/2f2560a073c93015e05d0baab0bf5e2853866e0f/extension.js#L15-L16

I need some more information to figure out why this is failing. Can you modify the file on disk at `/home/user/.vscode/extensions/zombocom.dead-end-vscode-0.1.2/extension.js` line 37 to add a `console.log(stderr)`. Then let me know what that outputs? (You can change it back when you're done).

@mauro-oto I'm just now realizing that the `dead_end` gem doesn't return a non-zeo status when it's found a syntax error. I could perhaps add that functionality to the gem and then this extension can check for status rather than output? (I'm not sure if it's related to this issue or not though without more information).

**Comment by OskarsEzerins** [comment]
Cannot reproduce anymore. Strange. Thanks for looking into this.
